test_folder = "pinny"
plotmode = "save" # show, save or both

injection_points = [
  "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7",
  "r8", "r9", "r10", "r11", "r12", "pc=*",
  "cpsr_n"
]

[pass_mode]
default = "returncode"

[pass_mode.returncode]
passed = 0
failed = 1
paniced = 2

[pass_mode.stdout]
expected_pass = "g_authenticated: 0"
expected_fail = "g_authenticated: 1"
